# Generated by Django 2.2 on 2020-11-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maple', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('references', models.TextField(max_length=2000)),
                ('previous_work', models.TextField(max_length=1000)),
                ('skills', models.TextField(max_length=1000)),
            ],
        ),
    ]
