# Generated by Django 2.2 on 2020-11-17 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maple', '0002_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='skills',
            new_name='job_position',
        ),
    ]
