# Generated by Django 2.2 on 2020-11-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maple', '0003_auto_20201117_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
