# Generated by Django 2.2 on 2020-11-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maple', '0004_menu_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='price',
            new_name='large',
        ),
        migrations.AddField(
            model_name='menu',
            name='regular',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
