# Generated by Django 2.2 on 2020-11-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maple', '0005_auto_20201119_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
