# Generated by Django 2.2 on 2020-11-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maple', '0006_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.CharField(default='https://www.google.com/search?q=default+image&rlz=1C1CHBD_enUS895US895&tbm=isch&source=iu&ictx=1&fir=dzPYWaGt8jz9-M%252Cajw91vrZ8GZcVM%252C_&vet=1&usg=AI4_-kRuzSNr1sPCfWp1LmdtUX6zo8IyyA&sa=X&ved=2ahUKEwjDotafv5ftAhXMWc0KHW97AtwQ9QF6BAgOEF8#imgrc=dzPYWaGt8jz9-M', max_length=500),
        ),
    ]
