# Generated by Django 2.2 on 2020-11-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maple', '0008_auto_20201122_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.CharField(default='https://www.takeoutlist.com/assets/images/food_default.png', max_length=500),
        ),
    ]
