# Generated by Django 2.2 on 2020-11-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maple', '0009_auto_20201122_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='images/none/noimg.jpg', upload_to='images'),
        ),
    ]
