# Generated by Django 2.2 on 2020-11-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maple', '0011_auto_20201124_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='images/non/noimg.jpg', upload_to='images'),
        ),
    ]
