# Generated by Django 2.2 on 2020-12-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maple', '0013_auto_20201124_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='profilepic.jpg', upload_to='food_pictures'),
        ),
    ]
