# Generated by Django 2.2 on 2020-12-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maple', '0018_auto_20201204_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='images', upload_to='Maple/images/none/noimg.jpg'),
        ),
    ]
