# Generated by Django 2.2 on 2020-12-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maple', '0026_auto_20201204_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chicken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('large', models.IntegerField()),
                ('regular', models.IntegerField()),
                ('image', models.CharField(default='https://www.takeoutlist.com/assets/images/food_default.png', max_length=500)),
            ],
        ),
    ]
