# Generated by Django 2.2 on 2020-12-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maple', '0028_beef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='image',
            field=models.ImageField(default='https://www.takeoutlist.com/assets/images/food_default.png', upload_to='images'),
        ),
    ]
