# Generated by Django 2.2 on 2020-12-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maple', '0029_auto_20201205_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beef',
            name='image',
            field=models.ImageField(default='https://www.takeoutlist.com/assets/images/food_default.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='https://www.takeoutlist.com/assets/images/food_default.png', upload_to='images'),
        ),
    ]
