# Generated by Django 2.2 on 2020-12-28 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maple', '0033_auto_20201228_1301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App',
            new_name='Menu',
        ),
    ]
