# Generated by Django 2.2 on 2020-12-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maple', '0035_auto_20201228_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='six',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='three',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
